---
driver:
  name: docker
platforms:
  - name: instance
    image: geerlingguy/docker-ubuntu2204-ansible:latest
    privileged: true
provisioner:
  name: ansible
  lint:
    name: ansible-lint
verifier:
  name: testinfra
