# reverse_proxy/tasks/main.yml
# Configures Nginx as a reverse proxy for n8n

- name: Include Nginx tasks
  include_tasks: nginx.yml

- name: Ensure Certbot renewal cron job exists
  cron:
    name: "Renew Let's Encrypt certificates with Certbot"
    user: root
    job: "certbot renew --quiet --post-hook 'systemctl reload nginx'"
    minute: 0
    hour: 3
    state: present
  tags: [letsencrypt, ssl]
  become: true
