# reverse_proxy/tasks/nginx.yml
- name: Install Nginx
  apt:
    name: nginx
    state: present
    update_cache: yes
  become: true

- name: Install Certbot and Nginx plugin
  apt:
    name:
      - certbot
      - python3-certbot-nginx
    state: present
    update_cache: yes
  become: true

- name: Deploy temporary HTTP-only Nginx config for certificate validation
  template:
    src: n8n-http.conf.j2
    dest: /etc/nginx/sites-available/n8n.conf
    owner: root
    group: root
    mode: 0644
  notify: reload nginx
  become: true

- name: Enable n8n site
  file:
    src: /etc/nginx/sites-available/n8n.conf
    dest: /etc/nginx/sites-enabled/n8n.conf
    state: link
    force: yes
  notify: reload nginx
  become: true

- name: Remove default site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: reload nginx
  become: true

- name: Ensure Nginx is reloaded before certificate request
  meta: flush_handlers

- name: Obtain/renew Let's Encrypt certificate with Certbot
  command: certbot --nginx --non-interactive --agree-tos --redirect -d {{ n8n_domain }} --email {{ n8n_admin_email }}
  notify: reload nginx
  become: true

- name: Deploy final hardened Nginx config with SSL
  template:
    src: n8n.conf.j2
    dest: /etc/nginx/sites-available/n8n.conf
    owner: root
    group: root
    mode: 0644
  notify: reload nginx
  become: true

- name: Set up logrotate for Nginx logs
  copy:
    src: logrotate-nginx
    dest: /etc/logrotate.d/nginx
    owner: root
    group: root
    mode: 0644
  become: true

# ModSecurity and advanced TLS/OCSP/HSTS are handled in the template.
