name: CI
on:
  pull_request:
    branches: [ main ]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Ansible & Molecule
        run: |
          pip install ansible ansible-lint molecule[docker]
      - name: Lint Ansible
        run: ansible-lint .
      - name: Molecule Test
        run: |
          cd molecule/default
          molecule test
